import "./js/toggleTheme";
import "./js/modalWindow";
import "./js/birthday";
import "./js/guess_num";
import "./js/calculator";
import "./js/dinasour";
import "./js/max-number";
import "./js/slider";
import "./js/footer";
